M48
; DRILL file {KiCad 9.0.2} date 2025-06-21T13:29:32+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-21T13:29:32+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X29.21Y-30.48
X29.21Y-149.86
X148.59Y-30.48
X148.59Y-149.86
M30
