name: Build

on:
  push:
  pull_request:

jobs:

  build-testrom:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make nasm git

      - name: Build ROM
        run: |
          cd src/uartboard
          make